CREATE DATABASE Ress;
USE Ress;
CREATE TABLE Customer (
	Id					INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Full_Name			VARCHAR(200) NOT NULL,
    Phone				VARCHAR(20) NOT NULL,
    Number_people		INT NOT NULL,
    Arrive_time			DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Dishes (
	Id				INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Dish_name		VARCHAR(200) NOT NULL,
	Price			FLOAT NOT NULL
);

CREATE TABLE Ordering (
	Id				INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CustomerId		INT NOT NULL REFERENCES Customer(Id)
);

CREATE TABLE Dishes_Ordering (
	Id				INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DishesId		INT NOT NULL REFERENCES Dishes(Id),
    OrderingId		INT NOT NULL REFERENCES Ordering(Id),
	Quantity		INT NOT NULL
);
select * from Customer

